### ISSUE TITLE
Coveralls broken in its 3.0 release

### ISSUE THREAD

**Issue by dmyersturnbull** [dmyersturnbull/tyrannosaurus#30]
Apparently COVERALLS_TOKEN is no longer needed.

```yaml
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
run: ....
```
